postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: pg_port  # pg default port 5432
  wait_timeout: 5000
  username: pg_username
  password: pg_password
  host: ip_address
  reconnect: true

sqlite_settings: &sqlite_settings
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *sqlite_settings
  database: db/development.sqlite3

test:
  <<: *postgresql_settings
  database: test

production:
  <<: *postgresql_settings
  database: production
